### ISSUE TITLE
Proxy chains?

### ISSUE THREAD

**Issue by zorro765** [JoshGlazebrook/socks#11]
Hey there, I would like to create proxy chains but can't figure out how. Can someone point me in the right direction? Kind regards.

**Comment by JoshGlazebrook** [comment]
I've thought about adding chaining as a feature. It shouldn't be too difficult.

**Comment by zorro765** [comment]
Would you mind sharing your thoughts / approach?

**Comment by JoshGlazebrook** [comment]
I previously was working on a C# library that featured proxy chaining when using the CONNECT request. The problem was finding 3 proxies that would actually work all at the same time was very hard to do. With a collection of 100 or so "working" ones, I would say 1 in 50 times the chain actually was completed and worked.

In terms of this javascript library, it's not necessarily designed for it to be chain-able, but I'm thinking it wouldn't be too hard. The main thing that has to be implemented is the ability to pass in an existing Socket instance to createConnection() so that instead of creating a brand new Socket, it uses the existing one and just does the handshake. And then probably a chainable function or add in an options slot to tell createConnection() it's a chain, and give it an array of proxy objects.

I don't have any timeline on it.

**Comment by JoshGlazebrook** [comment]
The general idea is:

You have proxy 1, proxy 2, and proxy 3. And then a destination host.


create new socket
connect to proxy 1, perform handshake for connect, telling it the destination host is proxy 2.
when proxy 1 handshake is done and its connected to proxy 2, perform handshake on proxy 2 telling it the destination host is proxy 3. When handshake is done for proxy 2, send the handshake for proxy 3 telling it the destination host you want in the end after the chain. When that handshake is done, you have a chain.

You -> proxy 1 -> proxy 2 -> proxy 3 -> destination host

**Comment by JoshGlazebrook** [comment]
V2 is now published and available. Proxy chaining is here!
