### ISSUE TITLE
How to Get Rid of Extra Packet

### ISSUE THREAD

**Issue by Miserlou** [JoshGlazebrook/socks#16]
Can you please go into a bit more detail about the 'Extra Packet' mentioned in the README?

I'm using this a proxy a lot of connections that aren't fault-tolerant, so it looks like like that extra packet is causing some problems.

Can you go into a bit more detail about why it's there, how to identify it, and how to get rid of it? Does it only appear in BIND mode? Should I try to identify it via its contents, length, or sequence?

**Comment by JoshGlazebrook** [comment]
As far as I know it only appears in the BIND mode in the format on the read me. It should be able to be detectable since it's the first data coming in and is limited to those few bytes. 

As far as testing it, it was incredibly difficult to find any public proxies that support anything other than connect.

**Comment by Miserlou** [comment]
Gotcha, thanks!
